CREATE TABLE users(
    id int primary key generated by default as identity,
    email varchar(50) unique not null,
    registration_date timestamp
);

CREATE TABLE recipes(
    id int primary key generated by default as identity,
    title varchar(50) not null,
    description varchar(500) not null,
    author_id int not null references users(id)
);

INSERT INTO users(email, registration_date)
values
('ivanoff256@gmail.com', now()),
('petroff256@gmail.com', now()),
('smirnoff256@gmail.com', now());

INSERT INTO recipes(title, description, author_id)
values
('Борщ', 'Сегодня в каждой семье есть свой рецепт борща. В кастрюлю добавляют и фасоль, и грибы, и копчёности, и даже сельдерей. Мы же научим вас готовить идеальный традиционный борщ.', 1),
('Блины', 'Подготовим все ингредиенты. Хорошо, если все они будут комнатной температуры, тогда они лучше соединятся. Поэтому лучше достаньте яйца (3 шт.) и молоко (500 мл) из холодильника заранее. Масло (30 г или 2 ст. ложки) можно использовать как растительное рафинированное (без запаха), так и сливочное. Сливочное масло придаёт блинчикам большую румяность и сливочный вкус. Если используете сливочное масло, то его необходимо растопить и дать ему остыть.', 2)

